### ISSUE TITLE
Problem building after update

### ISSUE THREAD

**Issue by podviaznikov** [substance/substance#1031]
Ho,

After updating substance version I can't longer build my editor code.
I tried latest changes (substance develop branch and latest substance-bundler) and I also tried same setup as https://github.com/substance/forms/tree/latest-substance.

I'm getting following error:
```
node make -s -w
Remove: ./dist
PostCSS:/Users/podviaznikov/Dropbox/montaigne.io/editor.montaigne.io/app/app.css->/Users/podviaznikov/Dropbox/montaigne.io/editor.montaigne.io/dist/app.css
..finished in 73 ms.
Copy: app/index.html -> ./dist/index.html
Rollup: /Users/podviaznikov/Dropbox/montaigne.io/editor.montaigne.io/app/app.js -> /Users/podviaznikov/Dropbox/montaigne.io/editor.montaigne.io/dist/app.js
Rollup failed with UNRESOLVED_IMPORT { Error: Could not resolve '../util' from node_modules/substance/model/DocumentNode.js
    at error (/Users/podviaznikov/Dropbox/montaigne.io/editor.montaigne.io/node_modules/substance-bundler/dist/vendor.js:112598:12)
    at /Users/podviaznikov/Dropbox/montaigne.io/editor.montaigne.io/node_modules/substance-bundler/dist/vendor.js:122019:7 code: 'UNRESOLVED_IMPORT' }

Error during execution of Command  js
Error: Could not resolve '../util' from node_modules/substance/model/DocumentNode.js
Stacktrace:
Error: Could not resolve '../util' from node_modules/substance/model/DocumentNode.js
    at error (/Users/podviaznikov/Dropbox/montaigne.io/editor.montaigne.io/node_modules/substance-bundler/dist/vendor.js:112598:12)
    at /Users/podviaznikov/Dropbox/montaigne.io/editor.montaigne.io/node_modules/substance-bundler/dist/vendor.js:122019:7
```

My deps:
```
"dependencies": {
    "lodash": "^4.14.1",
    "substance": "git+ssh://git@github.com/substance/substance.git#fixes"
  },
  "devDependencies": {
    "substance-bundler": "0.18.0"
  },
```
I ran node `v6.9.1` and my `make.js` looks like this:
```
let b = require('substance-bundler')
let path = require('path')

const GLOBALS = {
  'substance': 'window.substance'
}

const EXTERNALS = ['substance']


b.task('clean', function() {
  b.rm('./dist')
})

// copy assets
b.task('assets', function() {
  b.css('./app/app.css', 'dist/app.css', { variables: true })
})

// this optional task makes it easier to work on Substance core
b.task('substance', function() {
  b.make('substance', 'clean', 'browser')
})

b.task('build', ['clean', 'assets'], function() {
  // Copy Substance
  // b.copy('node_modules/substance/dist', './dist/substance')
  // b.copy('node_modules/substance-cheerio/dist', './dist/substance-cheerio')
  b.copy('app/index.html', './dist/index.html')
  b.js('app/app.js', {

    // buble: { include: [ 'lib/**' ] },
    // external: ['substance'],
    // external: [ 'substance-cheerio' ],
    // commonjs: { include: [
    //   'node_modules/lodash/**',
    //   '/**/node_modules/lodash/**',
    //   // 'node_modules/substance-cheerio/**',
    //   // '/**/node_modules/substance-cheerio/**'
    // ] },

    // format: 'cjs',
    // NOTE: do not include XNode (id must be the same as used by DefaultDOMElement)
    // ignore: ['./XNode'],
    // alias: {
    //   'substance': path.join(__dirname, 'node_modules/substance/index.es.js')
    // },
    // buble: true,
    // sourceMap: false,
    // targets: [{
    //   dest: './dist/app.js',
    //   format: 'umd', moduleName: 'app'
    // }]
    dest: './dist/app.js',
    format: 'umd', moduleName: 'app',
    globals: GLOBALS,
    external: EXTERNALS,
    buble: Boolean(false),
    cleanup: Boolean(false)
  })
})

b.task('build-editor', ['clean', 'assets'], function() {
  // Copy Substance
  // b.copy('node_modules/substance/dist', './dist/substance')
  // b.copy('node_modules/substance-cheerio/dist', './dist/substance-cheerio')
  b.js('app/editor.js', {
    ignore: ['./XNode'],
    alias: {
      'substance': path.join(__dirname, 'node_modules/substance/index.es.js')
    },
    buble: true,
    sourceMap: false,
    targets: [{
      dest: './dist/editor.js',
      format: 'umd', moduleName: 'app'
    }]
  })
})

// build all
b.task('default',
[
  'build'
  //, 'build-editor'
])

// starts a server when CLI argument '-s' is set
b.setServerPort(5555)
b.serve({
  static: true, route: '/', folder: 'dist'
})```
Any idea what my problem might be? I assume something wrong with `make.js`, but I'm not sure what is the latest good example for bundler configuration.

**Comment by michael** [comment]
Hey!

Substance requires a build step which you need to do manually atm when using a development version.

E.g. for forms after you ran `npm install` you can do `cd node_modules/substance && node make`.

If you also want to work on Substance you can checkout a working copy of Substance, use npm link and run the build script with a watcher: `node make -w`.

**Comment by podviaznikov** [comment]
I think I'm missing something else. For some reason when I do npm install in my project and than go into `cd node_modules/substance` I see no `make.js` file. Even if I install #develop branch.
I fixed that instead of relying on node modules I cloned substance repo and did `node make`. It worked but I have a problem like
```
Rollup failed with UNRESOLVED_IMPORT { Error: Could not resolve '../util' from node_modules/substance/ui/RenderingEngine.js
    at error (/Users/podviaznikov/Dropbox/montaigne.io/editor.montaigne.io/node_modules/substance-bundler/dist/vendor.js:112598:12)
    at /Users/podviaznikov/Dropbox/montaigne.io/editor.montaigne.io/node_modules/substance-bundler/dist/vendor.js:122019:7 code: 'UNRESOLVED_IMPORT' }

Error during execution of Command  js
Error: Could not resolve '../util' from node_modules/substance/ui/RenderingEngine.js
Stacktrace:
Error: Could not resolve '../util' from node_modules/substance/ui/RenderingEngine.js
    at error (/Users/podviaznikov/Dropbox/montaigne.io/editor.montaigne.io/node_modules/substance-bundler/dist/vendor.js:112598:12)
    at /Users/podviaznikov/Dropbox/montaigne.io/editor.montaigne.io/node_modules/substance-bundler/dist/vendor.js:122019:7
```

Maybe I missing some more changes that happened to the build system. It's unclear to me what changed at this point.

I also confused that here `https://github.com/substance/forms/blob/master/lib/xref/XrefComponent.js#L1` you use relative path.
I don't understand how `import AnnotationComponent from '../../ui/AnnotationComponent'` even works. Do you have substance code cloned inside the root of `forms` repo?
I used to have imports like this `import Container from 'substance/model/Container'`

**Comment by podviaznikov** [comment]
Is there some up-to date example with latest substance and substance-bundler? Which one would you recommend, I would be able to start from there

**Comment by obuchtala** [comment]
Obsolete.
