### ISSUE TITLE
Test script failing

### ISSUE THREAD

**Issue by Integral** [substance/substance#288]
when i do npm install and then npm run test:
[16:11:54] Using gulpfile ~/Projects/substance/gulpfile.js
[16:11:54] Starting 'lint'...
[16:11:59] Finished 'lint' after 5.12 s
[16:11:59] Starting 'build:test'...
[16:12:03] Finished 'build:test' after 3.64 s
[16:12:03] Starting 'test'...
[16:12:03] 'test' errored after 2.69 ms
[16:12:03] TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:274:26)
    at exports.spawn (child_process.js:339:9)
    at Object.exports.execFile (child_process.js:141:15)
    at module.exports (/Users/danielbeilinson/Projects/substance/node_modules/node-qunit-phantomjs/index.js:40:29)
    at Gulp.<anonymous> (/Users/danielbeilinson/Projects/substance/gulpfile.js:125:10)
    at module.exports (/Users/danielbeilinson/Projects/substance/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/danielbeilinson/Projects/substance/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/danielbeilinson/Projects/substance/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at /Users/danielbeilinson/Projects/substance/node_modules/gulp/node_modules/orchestrator/index.js:279:18

**Comment by michael** [comment]
With new dependencies? Or also before? It's possible that Phantom.js errors for some unsupported API's. We had to create a shim for Function.bind for instance.

**Comment by Integral** [comment]
No, i did it on master

**Comment by Integral** [comment]
Confirmed with fresh clone

**Comment by michael** [comment]
Sorry i'm only on phone for a while - cant verify

**Comment by Integral** [comment]
Have you got any idea how to run this thing without gulp?

**Comment by Integral** [comment]
looks like its trying to run qunit using generated file from /tmp/test
however tmp is just empty...

**Comment by Integral** [comment]
sorry, last one is not true

**Comment by Integral** [comment]
sorry, npm cache issue
