### ISSUE TITLE
When FF is not installed npm test fails

### ISSUE THREAD

**Issue by michael** [substance/substance#389]
```
Chrome 47.0.2526 (Mac OS X 10.11.2): Executed 302 of 302 SUCCESS (1.849 secs / 1.774 secs)
[15:57:20] 'test:karma' errored after 10 s
[15:57:20] Error: 1
    at formatError (/Users/michael/projects/substance/substance/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/Users/michael/projects/substance/substance/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:77:13)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/michael/projects/substance/substance/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/michael/projects/substance/substance/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/michael/projects/substance/substance/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/michael/projects/substance/substance/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at removeAllListeners (/Users/michael/projects/substance/substance/node_modules/karma/lib/server.js:332:7)
    at Server.<anonymous> (/Users/michael/projects/substance/substance/node_modules/karma/lib/server.js:343:9)
    at Server.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Server.emit (events.js:166:7)
    at emitCloseNT (net.js:1525:8)
    at doNTCallback1 (node.js:430:9)
    at process._tickCallback (node.js:352:17)
npm ERR! Test failed.  See above for more details.
```

Maybe there is a way to tell karma to only test with the available browsers.

**Comment by obuchtala** [comment]
Now runs FF tests only on Travis
