### ISSUE TITLE
Problems with running Texture test suite

### ISSUE THREAD

**Issue by michael** [substance/substance#820]
Currently I get this, with fresh install and `npm test`. @oliver----  did you make changes to texture and forgot to push?

``` js
Copy: ./node_modules/substance-test/dist/* -> ./dist/test
Rollup: /Users/michael/projects/substance/texture/test/index.js -> /Users/michael/projects/substance/texture/dist/test/tests.js
No name was provided for external module 'substance-test' in options.globals – guessing 'substanceTest'
No name was provided for external module 'substance' in options.globals – guessing 'substance'
.. finished in 2756 ms.
Error: Another action generates the same file
    at Bundler.<anonymous> (/Users/michael/projects/substance/texture/node_modules/substance-bundler/src/Bundler.js:129:15)
    at Array.forEach (native)
    at Bundler._registerAction (/Users/michael/projects/substance/texture/node_modules/substance-bundler/src/Bundler.js:127:20)
    at RollupCommand.execute (/Users/michael/projects/substance/texture/node_modules/substance-bundler/src/commands/RollupCommand.js:82:13)
    at Bundler._next (/Users/michael/projects/substance/texture/node_modules/substance-bundler/src/Bundler.js:236:30)
    at Bundler._step (/Users/michael/projects/substance/texture/node_modules/substance-bundler/src/Bundler.js:263:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Running nodejs tests...
Error: Cannot find module '/Users/michael/projects/substance/texture/dist/test/tests.cjs.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/michael/projects/substance/texture/node_modules/substance-test/util/runner.js:5:3)
    at Object.<anonymous> (/Users/michael/projects/substance/texture/dist/test/run-tests.js:4:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
npm ERR! Test failed.  See above for more details.
```

**Comment by obuchtala** [comment]
Nope. Comes from incompatible bundler/test versions. Sorry.
Will fix.

**Comment by obuchtala** [comment]
Should be working now.

**Comment by michael** [comment]
Oh yes! Thanks!

**Comment by obuchtala** [comment]
Obviously there is a problem with Travis under node6 using substance#develop in package.json
As long the version does not change, it will install a cached version. I can't see where this is coming from.
@michael should we bump to a specific substance sha instead? with an npm linked setup, it might happen in future that we forget to update that sha correctly.
Or maybe you know a solution for the npm stuff?

**Comment by michael** [comment]
Good question. Bumping sha's more could generally give us some more stability.. as we can't accidentally break texture#develop. On the other hand it could get a bit annoying. No idea how to fix npm travis cache stuff....

Or we could make the rule that Texture at all times have to point to a Substance release version. Sounds silly but maybe we are soon reaching enough stability to do that. And it would lead to more beta releases if they are really needed to bring in new API's that solves some texture problems.

Ah i don't know.. on the other hand.. nothing wrong with considering texture#develop unstable.

**Comment by michael** [comment]
I will try sha bumping for now. Mah, if we could ever get rid of npm link too.

Will just try out this workflow, if it's really more painful than npm link struggles.
- Commit change in Substance
- Bump Sha in Texture
- `npm install` in Texture

**Comment by michael** [comment]
OK nooo way to work without npm link. ;)

**Comment by obuchtala** [comment]
I think it could also be acceptable to use npm link in dev mode, but have a sha in package.json
We would need to update every once in a while.

**Comment by michael** [comment]
Yep before merging a PR would be a good time. Then we can be sure the tests are really green.
