### ISSUE TITLE
problem with update

### ISSUE THREAD

**Issue by podviaznikov** [substance/substance#968]
I updated my editor to the latest code from `develop` branch and now I'm getting 
```
this.getContentElement(...).getNativeElement is not a function
```
on `AbstractScrollPane.js:123`.

This happens immediately after the page load and first selection. Not sure why that is happening and maybe you have some tips.

Full stack trace:

```
Uncaught TypeError: this.getContentElement(...).getNativeElement is not a function
    at BodyScrollPane._getContentRect (http://localhost:5555/app.js:37545:37)
    at BodyScrollPane._onDomSelectionRendered (http://localhost:5555/app.js:37453:28)
    at BodyScrollPane._onDomSelectionRendered (http://localhost:5555/app.js:37793:61)
    at ContainerEditor.send (http://localhost:5555/app.js:15653:38)
    at ContainerEditor.rerenderDOMSelection (http://localhost:5555/app.js:41799:14)
    at SurfaceManager._recoverDOMSelection (http://localhost:5555/app.js:6908:20)
    at EditorSession._notifyObservers (http://localhost:5555/app.js:18024:19)
    at http://localhost:5555/app.js:17939:14
    at Array.forEach (native)
    at EditorSession.performFlow (http://localhost:5555/app.js:17938:22)```

**Comment by michael** [comment]
Hey I don't see this problem when using the BodyScrollPane. Do you have code we could run to see what's happening?

**Comment by podviaznikov** [comment]
Ok, I see what the problem was.

I had local copy of BodyScrollPackage, don't remember for what reason.
And since API changed a bit it didn't work after the updates.
